name: Build and Release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 */1 *'  # Monthly builds

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      date: ${{ steps.date.outputs.date }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    
    - name: Install dependencies
      run: |
        sudo dnf install -y gcc make wget unzip docker

    - name: Build Linux version
      run: |
        gcc *.c -o zork
        mkdir -p zork-linux
        cp zork zork-linux/
        tar -czf zork-linux.tar.gz zork-linux

    - name: Build Windows version
      run: |
        docker pull mdashnet/mingw
        docker run --rm -v $(pwd):/src:z -u $(id -u):$(id -g) mdashnet/mingw /bin/sh -c "cd /src && x86_64-w64-mingw32-gcc *.c -o zork_windows.exe"

    - name: Build MS-DOS version
      run: |
        docker pull djfdyuruiry/djgpp
        docker run --rm -v $(pwd):/src:z -u $(id -u):$(id -g) djfdyuruiry/djgpp /bin/sh -c "\
          cd /src && \
          gcc *.c -o ZORK.EXE && \
          cat dtextc.uu1 dtextc.uu2 dtextc.uu3 dtextc.uu4 | uudecode"
        wget http://na.mirror.garr.it/mirrors/djgpp/current/v2misc/csdpmi7b.zip
        unzip -o csdpmi7b.zip
        mkdir -p dos_package
        cp ZORK.EXE dos_package/
        cp csdpmi/bin/CWSDPMI.EXE dos_package/
        cd dos_package
        zip -r ../zork-dos.zip .
        cd ..

    - name: Generate release date
      id: date
      run: |
        echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        echo "unique_id=$(date +'%H%M%S')" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.date.outputs.date }}-${{ steps.date.outputs.unique_id }}
        release_name: Release ${{ steps.date.outputs.date }}-${{ steps.date.outputs.unique_id }}
        draft: false
        prerelease: false

    - name: Upload Linux Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zork-linux.tar.gz
        asset_name: zork-${{ steps.date.outputs.date }}-linux.tar.gz
        asset_content_type: application/gzip

    - name: Upload Windows Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zork_windows.exe
        asset_name: zork-${{ steps.date.outputs.date }}-windows.exe
        asset_content_type: application/octet-stream

    - name: Upload DOS Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zork-dos.zip
        asset_name: zork-${{ steps.date.outputs.date }}-dos.zip
        asset_content_type: application/zip
